name: 'Cleanup Runner'
description: 'Remove unnecessary files to free up disk space'
runs:
  using: "composite"
  steps:
    - name: Remove unnecessary files
      shell: bash
      run: |
        df -h
        echo "PACKER_DOCKER_FILE: $PACKER_DOCKER_FILE"
        sudo docker system prune -a -f --volumes
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/share/dotnet
        df -h
