name: Docker Build and Push

on:
  push:
    branches: [ '**' ]
  schedule:
    - cron:  '30 7 * * *'
  pull_request:
    branches: [ main ]

jobs:
  docker-lite:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell"
          testing: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push lite
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-lite
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/skillarch:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/skillarch:lite
            ${{ secrets.DOCKERHUB_USERNAME }}/skillarch:lite-${{ github.sha }}

      - name: Build and Push full
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-full
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/skillarch:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/skillarch:full
            ${{ secrets.DOCKERHUB_USERNAME }}/skillarch:full-${{ github.sha }}
